controllers:
    resource: ../src/Controller/
    type: attribute

filterProduct:
    path: /filter
    controller : App\Controller\ProductPageController::filter



cart:
    path : /cart
    controller : App\Controller\ProductPageController::cart


logout:
    path: /logout
